# key=original name, values=map names
columns_to_retain = {# methodological variables
                     "B_COUNTRY": "country",                   
                     "D_INTERVIEW": "interview",
                     "Q_MODE": "mode",
                     "H_SETTLEMENT": "settlment",    
                     "H_URBRURAL": "urbrural",
                     "E_RESPINT": "respint",
                     "E1_LITERACY": "literacy",
                     "F_INTPRIVACY": "intprivacy",
                     "W_WEIGHT": "weight",        
                     "S018": "s018",
                     # demographic variables
                     "Q260": "sex",                            
                     "Q261": "birth_year",
                     "Q262": "age",
                     "Q263": "immigrant",
                     "Q264": "mother_immigrant",
                     "Q265": "father_immigrant",
                     "Q266": "birth_country",
                     "Q267": "mother_birth_country",
                     "Q268": "father_birth_country",
                     "Q269": "citizenship",
                     "Q270": "household_size",
                     "Q271": "lives_with_parents",
                     "Q272": "household_language",
                     "Q273": "martial_status",
                     "Q274": "children_number",
                     "Q275R": "education_level",
                     "Q276R": "spouse_education_level",
                     "Q277R": "mother_education_level",
                     "Q279": "employment",
                     "Q280": "spouse_employment",
                     "Q281": "occupation",
                     "Q282": "spouse_occupation",
                     "Q283": "father_occupation",
                     "Q284": "employment_sector",
                     "Q285": "chief_earner",
                     "Q286": "savings",
                     "Q287": "subjective_social_class",
                     "Q288R": "income_scale",
                     "Q289": "religion",
                     # political variables
                     "Q209": "signed_petitions",                 
                     "Q210": "joined_boycotts",
                     "Q211": "attended_peaceful_demonstration",
                     "Q212": "joined_unofficial_strikes",
                     "Q213": "donated_campaign",
                     "Q214": "contacted_government",
                     "Q215": "encouraged_political_action",
                     "Q216": "encouraged_voting",
                     "Q217": "fosters_political_knowledge",
                     "Q218": "signed_petitions_online",
                     "Q219": "encouraged_political_action_online",
                     "Q220": "organized_political_events",
                     "Q221": "voted_locally",
                     "Q222": "voted_nationally"
}